alias ..='cd ..'
alias ...='cd ../..'
alias brow='/usr/local/homebrew/bin/brew'
alias n='nvim'

alias cat='bat'
alias cp='cp -i'
alias df='df -h'
alias du='du -h'
alias ls='eza --all --git --group-directories-first --header --long --time-style long-iso'
alias mkdir='mkdir -p'
alias mv='mv -i'
alias rg='rg --ignore-case'
alias rm='rm -i'
