# Linux Aliases Part 1
alias cp="cp -i"
alias df="df -h"
alias du="du -h"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias free="free -h"
alias grep="grep --color=auto"
alias ls="ls --color=auto"
alias mkdir="mkdir -p"
alias mv="mv -i"
alias ping="ping -c 5"
alias rm="rm -i"

# Linux Aliases Part 2
alias ...="cd ../.."
alias ..="cd .."
alias hg="history | grep"
alias ll="ls -lAh"
alias lzd="lazydocker"
alias lzg="lazygit"
alias ports="ss -tulpn"

# macOS Aliases Part 1
alias brow="/usr/local/homebrew/bin/brew"
alias n="nvim"
alias rg="rg --ignore-case"
alias ll="eza --all --git --group-directories-first --header --long --time-style long-iso"
alias ports="viddy --interval 1s 'lsof -i @127.0.0.1 | grep LISTEN'"
alias ping="ping"
