#!/usr/bin/env bash
#MISE description="Generate agent prompt files (AGENTS.md/CLAUDE.md) from modules/agents/"

set -euo pipefail

# shellcheck source=.mise/scripts/task-lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/../scripts/task-lib.sh"

dotfiles_enter_repo
dotfiles_require_commands gum

force=0
[ "${1:-}" = "--force" ] && force=1

base="modules/agents/base.md"
header="<!-- generated by 'mise run agents' from modules/agents/; edit sources there -->"
drifted=()

generate() {
  local appendix="$1" target="$2" snapshot="$3" tmp

  # The snapshot records what the generator last wrote. If the live target has
  # diverged from it, someone edited the artifact; refuse to clobber the edit.
  if [ "$force" -eq 0 ] && [ -f "$target" ] && [ -f "$snapshot" ] \
    && ! cmp -s "$target" "$snapshot"; then
    gum log --level warn "$target edited since last generation; skipping. Diff vs last generated:"
    diff -u "$snapshot" "$target" || true
    drifted+=("$target")
    return 0
  fi

  tmp="$(mktemp "${TMPDIR:-/tmp}/agents.XXXXXX")"
  {
    printf '%s\n\n' "$header"
    cat "$base"
    printf '\n'
    cat "$appendix"
  } >"$tmp"

  mkdir -p "$(dirname "$target")" "$(dirname "$snapshot")"
  install -m 600 "$tmp" "$target"
  install -m 600 "$tmp" "$snapshot"
  rm -f "$tmp"

  gum log --level info "Generated $target (+ $snapshot)"
}

generate modules/agents/codex.md  "$HOME/.codex/AGENTS.md"      home/.codex/AGENTS.md
generate modules/agents/claude.md "$HOME/.claude/CLAUDE.md"     home/.claude/CLAUDE.md
generate modules/agents/amp.md    "$HOME/.config/amp/AGENTS.md" home/.config/amp/AGENTS.md

if [ "${#drifted[@]}" -gt 0 ]; then
  gum log --level error \
    "Drift detected. Port edits worth keeping into modules/agents/, then overwrite the live files with: mise run agents --force"
  exit 1
fi
