import json
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

from scripts.runtime import (
    RuntimeReport,
    RuntimeAction,
    RuntimeResult,
    RuntimeSpec,
    RuntimeStatus,
    _next_commands,
    execute_runtime,
    plan_runtime,
)


def _fake_tool(bin_dir: Path, name: str, body: str = "exit 0\n") -> None:
    tool_path = bin_dir / name
    tool_path.write_text(f"#!/bin/sh\n{body}")
    tool_path.chmod(0o755)


def _run_runtime(
    repo_root: Path,
    home: Path,
    bin_dir: Path,
    *arguments: str,
) -> subprocess.CompletedProcess[str]:
    environment = os.environ.copy()
    environment["HOME"] = str(home)
    environment["PATH"] = str(bin_dir)
    return subprocess.run(
        [
            sys.executable,
            "-m",
            "scripts.runtime",
            "--repo-root",
            str(repo_root),
            *arguments,
        ],
        cwd=Path(__file__).resolve().parents[1],
        env=environment,
        check=False,
        capture_output=True,
        text=True,
    )


def test_runtime_previews_owned_refresh_by_default_without_writing(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("mise", "starship", "atuin", "codex", "git", "bat"):
        _fake_tool(bin_dir, name)

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--json",
    )

    assert completed.returncode == 0
    document = json.loads(completed.stdout)
    assert document["schema_version"] == 1
    assert document["operation"] == "runtime"
    assert document["apply"] is False
    steps = {step["name"]: step for step in document["steps"]}
    assert steps["function.mise"]["action"] == "generate"
    assert steps["function.starship"]["status"] == "planned"
    assert steps["function.atuin"]["status"] == "planned"
    assert steps["completion.codex"]["action"] == "generate"
    assert steps["completion.op"]["status"] == "skipped"
    assert steps["plugin.fzf-tab"]["action"] == "clone"
    assert steps["plugin.zsh-autosuggestions"]["action"] == "clone"
    assert steps["plugin.fast-syntax-highlighting"]["action"] == "clone"
    assert steps["wasm.zellij-sessionizer"]["action"] == "download"
    assert steps["wasm.zjstatus"]["action"] == "download"
    assert steps["bat.cache"]["status"] == "planned"
    assert steps["zsh.compdump"]["status"] == "skipped"
    assert steps["zsh.compdump"]["target"] == str(home / ".zcompdump*")
    assert document["summary"] == {"planned": 10, "skipped": 9}
    assert not (repo_root / "generated").exists()


def test_runtime_offline_apply_generates_and_removes_owned_shell_files(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    completions = repo_root / "generated/completions"
    completions.mkdir(parents=True)
    home.mkdir()
    bin_dir.mkdir()
    stale_completion = completions / "_op"
    stale_completion.write_text("stale\n")
    legacy_try_rs = completions / "_try-rs"
    legacy_try_rs.write_text("legacy\n")
    compdump = home / ".zcompdump-test"
    compdump.write_text("cache\n")
    for name in ("mise", "starship", "atuin", "codex"):
        _fake_tool(bin_dir, name, f"printf 'generated by {name}: %s\\n' \"$*\"\n")

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--offline",
        "--apply",
        "--json",
    )

    assert completed.returncode == 0
    document = json.loads(completed.stdout)
    assert document["apply"] is True
    assert document["ok"] is True
    results = {step["name"]: step for step in document["steps"]}
    assert results["function.mise"]["status"] == "succeeded"
    assert results["completion.codex"]["status"] == "succeeded"
    assert results["completion.op"]["action"] == "remove"
    assert results["completion.op"]["status"] == "succeeded"
    assert results["plugin.fzf-tab"]["status"] == "skipped"
    assert results["wasm.zjstatus"]["status"] == "skipped"
    assert document["summary"] == {"skipped": 13, "succeeded": 7}
    assert (repo_root / "generated/functions/_mise.zsh").read_text() == (
        "generated by mise: activate zsh\n"
    )
    assert (completions / "_codex").read_text() == (
        "generated by codex: completion zsh\n"
    )
    assert not stale_completion.exists()
    assert not legacy_try_rs.exists()
    assert not compdump.exists()


def test_runtime_keeps_generating_for_self_built_tools_off_path(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    owned_bin = repo_root / "generated/bin"
    owned_bin.mkdir(parents=True)
    functions = repo_root / "generated/functions"
    functions.mkdir(parents=True)
    (functions / "_atuin.zsh").write_text("previously generated\n")
    _fake_tool(owned_bin, "atuin", "printf 'generated by owned atuin\\n'\n")

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply", "--json")

    assert completed.returncode == 0
    document = json.loads(completed.stdout)
    results = {step["name"]: step for step in document["steps"]}
    assert results["function.atuin"]["action"] == "generate"
    assert results["function.atuin"]["status"] == "succeeded"
    assert (functions / "_atuin.zsh").read_text() == "generated by owned atuin\n"

    (owned_bin / "atuin").unlink()
    removed = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply", "--json")

    assert removed.returncode == 0
    document = json.loads(removed.stdout)
    results = {step["name"]: step for step in document["steps"]}
    assert results["function.atuin"]["action"] == "remove"
    assert not (functions / "_atuin.zsh").exists()


def test_runtime_generates_llm_completion_through_uvx(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    completion = repo_root / "generated/completions/_llm"
    completion.parent.mkdir(parents=True)
    completion.write_text("stale\n")
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(
        bin_dir,
        "uvx",
        'test "$1" = --offline || exit 9\n'
        'test "$2" = llm || exit 7\n'
        'test "$_LLM_COMPLETE" = zsh_source || exit 8\n'
        "printf 'llm completion\\n'\n",
    )

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply", "--json")

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["completion.llm"]["status"] == "succeeded"
    assert steps["completion.llm"]["command"] == ["uvx", "--offline", "llm"]
    assert completion.read_text() == "llm completion\n"


def test_runtime_rejects_invalid_download_without_replacing_asset(
    tmp_path: Path,
) -> None:
    target = tmp_path / "plugin.wasm"
    target.write_bytes(b"known-good")
    expected = hashlib.sha256(b"new-valid").hexdigest()
    spec = RuntimeSpec(
        name="wasm.test",
        tool=None,
        target=target,
        source="https://example.invalid/plugin.wasm",
        sha256=expected,
    )
    plan = RuntimeReport(
        apply=False,
        results=(RuntimeResult(spec, RuntimeStatus.PLANNED, RuntimeAction.DOWNLOAD),),
    )

    report = execute_runtime(
        plan,
        tmp_path,
        downloader=lambda _source, _timeout: b"corrupt",
    )

    assert report.ok is False
    assert report.results[0].status is RuntimeStatus.FAILED
    assert "checksum mismatch" in (report.results[0].reason or "")
    assert target.read_bytes() == b"known-good"


def test_runtime_failed_preview_does_not_suggest_apply(tmp_path: Path) -> None:
    planned = RuntimeResult(
        RuntimeSpec(name="planned", tool=None, target=tmp_path / "planned"),
        RuntimeStatus.PLANNED,
        RuntimeAction.DOWNLOAD,
    )
    failed = RuntimeResult(
        RuntimeSpec(name="failed", tool=None, target=tmp_path / "failed"),
        RuntimeStatus.FAILED,
        RuntimeAction.CLONE,
        "target is not a Git checkout",
    )

    assert _next_commands(RuntimeReport(False, (planned, failed))) == ()


def test_runtime_build_plan_owns_custom_rust_binaries(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("git", "cargo"):
        _fake_tool(bin_dir, name)

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["source.atuin"]["action"] == "clone"
    assert steps["binary.atuin"]["action"] == "build"
    assert steps["source.op-cache"]["action"] == "clone"
    assert steps["binary.op-cache"]["action"] == "build"
    assert steps["binary.atuin"]["target"] == str(repo_root / "generated/bin/atuin")
    assert not (repo_root / "generated/sources").exists()


def test_runtime_build_installs_artifacts_from_portable_sources(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("atuin", "op-cache"):
        (repo_root / "generated/sources" / name / ".git").mkdir(parents=True)
    _fake_tool(
        bin_dir,
        "cargo",
        'case "$PWD" in\n'
        "  */atuin) binary=atuin ;;\n"
        "  */op-cache) binary=op-cache ;;\n"
        "esac\n"
        "/bin/mkdir -p target/release\n"
        'printf \'built %s\\n\' "$binary" > "target/release/$binary"\n'
        '/bin/chmod 755 "target/release/$binary"\n',
    )

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--offline",
        "--apply",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["source.atuin"]["status"] == "skipped"
    assert steps["binary.atuin"]["status"] == "succeeded"
    assert steps["binary.op-cache"]["status"] == "succeeded"
    assert (repo_root / "generated/bin/atuin").read_text() == "built atuin\n"
    assert (repo_root / "generated/bin/op-cache").read_text() == "built op-cache\n"


def test_runtime_does_not_build_from_stale_source_after_update_failure(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("atuin", "op-cache"):
        (repo_root / "generated/sources" / name / ".git").mkdir(parents=True)
    _fake_tool(bin_dir, "git", "exit 7\n")
    _fake_tool(bin_dir, "cargo", "touch build-ran\n")
    monkeypatch.setenv("PATH", str(bin_dir))

    def finder(tool: str) -> str | None:
        candidate = bin_dir / tool
        return str(candidate) if candidate.exists() else None

    plan = plan_runtime(repo_root, home, executable_finder=finder, build=True)
    report = execute_runtime(plan, home, downloader=lambda _url, _timeout: b"stub")

    results = {result.spec.name: result for result in report.results}
    assert report.ok is False
    assert results["source.atuin"].status is RuntimeStatus.FAILED
    assert results["binary.atuin"].status is RuntimeStatus.SKIPPED
    assert "source.atuin failed" in (results["binary.atuin"].reason or "")
    assert not (repo_root / "generated/sources/atuin/build-ran").exists()
    assert not (repo_root / "generated/sources/op-cache/build-ran").exists()


def test_runtime_failed_clone_never_publishes_partial_checkout(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    target = repo_root / "generated/plugins/example"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(
        bin_dir,
        "git",
        'for final_argument do :; done\n/bin/mkdir -p "$final_argument/.git"\nexit 7\n',
    )
    monkeypatch.setenv("PATH", str(bin_dir))
    spec = RuntimeSpec(
        name="plugin.example",
        tool="git",
        target=target,
        source="https://example.invalid/example.git",
        command=(
            "git",
            "clone",
            "--depth=1",
            "https://example.invalid/example.git",
            str(target),
        ),
    )
    report = execute_runtime(
        RuntimeReport(
            apply=False,
            results=(
                RuntimeResult(
                    spec,
                    RuntimeStatus.PLANNED,
                    RuntimeAction.CLONE,
                ),
            ),
        ),
        home,
    )

    assert report.ok is False
    assert report.results[0].exit_code == 7
    assert not target.exists()
    assert not list(target.parent.glob(".example.clone-*"))
    next_plan = plan_runtime(
        repo_root,
        home,
        executable_finder=lambda tool: str(bin_dir / tool) if tool == "git" else None,
    )
    next_result = next(
        result for result in next_plan.results if result.spec.name == "plugin.fzf-tab"
    )
    assert next_result.action is RuntimeAction.CLONE


def test_runtime_successful_clone_atomically_publishes_checkout(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    target = repo_root / "generated/plugins/example"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(
        bin_dir,
        "git",
        "for final_argument do :; done\n"
        '/bin/mkdir -p "$final_argument/.git"\n'
        'printf "checkout\\n" >"$final_argument/plugin.zsh"\n',
    )
    monkeypatch.setenv("PATH", str(bin_dir))
    spec = RuntimeSpec(
        name="plugin.example",
        tool="git",
        target=target,
        command=("git", "clone", "https://example.invalid/example.git", str(target)),
    )
    report = execute_runtime(
        RuntimeReport(
            apply=False,
            results=(
                RuntimeResult(
                    spec,
                    RuntimeStatus.PLANNED,
                    RuntimeAction.CLONE,
                ),
            ),
        ),
        home,
    )

    assert report.ok is True
    assert (target / ".git").is_dir()
    assert (target / "plugin.zsh").read_text() == "checkout\n"
    assert not list(target.parent.glob(".example.clone-*"))


def test_runtime_offline_build_is_locked_and_offline(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    (repo_root / "generated/sources/atuin/.git").mkdir(parents=True)
    (repo_root / "generated/sources/op-cache/.git").mkdir(parents=True)
    _fake_tool(bin_dir, "cargo")

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--offline",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    for name in ("atuin", "op-cache"):
        command = steps[f"binary.{name}"]["command"]
        assert "--locked" in command
        assert "--offline" in command


def test_runtime_online_build_requires_git_to_refresh_existing_source(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("atuin", "op-cache"):
        (repo_root / "generated/sources" / name / ".git").mkdir(parents=True)
    _fake_tool(bin_dir, "cargo")

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["source.atuin"]["status"] == "skipped"
    assert steps["binary.atuin"]["status"] == "skipped"
    assert steps["binary.atuin"]["reason"] == "git is not available"


def test_runtime_human_mode_announces_work_and_reports_failure_to_stderr(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(bin_dir, "mise", "exit 7\n")
    _fake_tool(bin_dir, "codex", "printf 'codex completion\\n'\n")

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply")

    assert completed.returncode == 1
    assert completed.stdout.splitlines()[0] == (
        "RUN function.mise: mise activate zsh -> "
        f"{repo_root}/generated/functions/_mise.zsh"
    )
    assert "[function.mise] FAIL command exited 7" in completed.stderr
    assert (repo_root / "generated/completions/_codex").read_text() == (
        "codex completion\n"
    )


def test_runtime_announces_the_exact_compdump_pattern(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    (home / ".zcompdump-test").write_text("cache\n")

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply")

    assert completed.returncode == 0
    assert completed.stdout.splitlines()[0] == (
        f"RUN zsh.compdump: remove {home}/.zcompdump*"
    )
    assert not (home / ".zcompdump-test").exists()


def test_runtime_human_preview_shows_commands_and_targets(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(bin_dir, "codex")

    completed = _run_runtime(repo_root, home, bin_dir, "--offline")

    assert completed.returncode == 0
    assert (
        "PLANNED completion.codex: codex completion zsh -> "
        f"{repo_root}/generated/completions/_codex"
    ) in completed.stdout


def test_runtime_preview_does_not_suggest_apply_when_every_step_is_skipped(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()

    completed = _run_runtime(repo_root, home, bin_dir, "--offline")

    assert completed.returncode == 0
    assert "No runtime refresh steps are available" in completed.stdout
    assert "--apply" not in completed.stdout


def test_runtime_surfaces_operational_output_but_keeps_json_on_stdout(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(
        bin_dir,
        "bat",
        "printf 'cache rebuilt\\n'\nprintf 'cache note\\n' >&2\n",
    )

    human = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply")
    machine = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--offline",
        "--apply",
        "--json",
    )

    assert human.returncode == 0
    assert "cache rebuilt" in human.stdout
    assert "cache note" in human.stderr
    assert machine.returncode == 0
    assert json.loads(machine.stdout)["ok"] is True
    assert "[bat.cache] cache rebuilt" in machine.stderr
    assert "[bat.cache] cache note" in machine.stderr


def test_runtime_json_keeps_captured_failure_detail(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(bin_dir, "bat", "printf 'cache failed\\n' >&2\nexit 7\n")

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--offline",
        "--apply",
        "--json",
    )

    result = next(
        step
        for step in json.loads(completed.stdout)["steps"]
        if step["name"] == "bat.cache"
    )
    assert completed.returncode == 1
    assert result["reason"] == "command exited 7: cache failed"
    assert result["exit_code"] == 7
    assert "[bat.cache] cache failed" in completed.stderr


def test_runtime_partial_apply_keeps_exit_code_and_restart_handoff(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(bin_dir, "mise", "exit 7\n")
    _fake_tool(bin_dir, "codex", "printf 'codex completion\\n'\n")

    machine = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--offline",
        "--apply",
        "--json",
    )
    human = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply")

    document = json.loads(machine.stdout)
    failed = next(step for step in document["steps"] if step["name"] == "function.mise")
    assert machine.returncode == 1
    assert failed["exit_code"] == 7
    assert document["shell_restart_required"] is True
    assert document["next"] == []
    assert human.returncode == 1
    assert "Refreshed Zsh runtime is not active in the current shell." in human.stdout
    assert "Open a new Zsh or run `exec zsh`" in human.stdout
    assert "Next:" not in human.stdout


def test_runtime_cli_runs_real_mise_in_an_isolated_home(tmp_path: Path) -> None:
    mise = shutil.which("mise")
    if mise is None:
        raise AssertionError("mise is required to verify this repository")
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    (bin_dir / "mise").symlink_to(Path(mise).resolve())

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply", "--json")

    assert completed.returncode == 0, completed.stderr
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["function.mise"]["status"] == "succeeded"
    activation = repo_root / "generated/functions/_mise.zsh"
    assert activation.is_file()
    assert "mise" in activation.read_text()


def test_runtime_refuses_to_clobber_non_git_plugin_dirs(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(bin_dir, "git")
    (repo_root / "generated/plugins/fzf-tab").mkdir(parents=True)

    completed = _run_runtime(repo_root, home, bin_dir, "--json")

    assert completed.returncode == 1
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["plugin.fzf-tab"]["status"] == "failed"
    assert "not a Git checkout" in steps["plugin.fzf-tab"]["reason"]


def test_runtime_keeps_old_output_when_generator_prints_nothing(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    functions = repo_root / "generated/functions"
    functions.mkdir(parents=True)
    (functions / "_mise.zsh").write_text("previous good output\n")
    _fake_tool(bin_dir, "mise", "exit 0\n")

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--apply", "--json")

    assert completed.returncode == 1
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["function.mise"]["status"] == "failed"
    assert (functions / "_mise.zsh").read_text() == "previous good output\n"
