import json
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

from scripts.runtime import (
    RuntimeReport,
    RuntimeAction,
    RuntimeResult,
    RuntimeSpec,
    RuntimeStatus,
    execute_runtime,
)


def _fake_tool(bin_dir: Path, name: str, body: str = "exit 0\n") -> None:
    tool_path = bin_dir / name
    tool_path.write_text(f"#!/bin/sh\n{body}")
    tool_path.chmod(0o755)


def _run_runtime(
    repo_root: Path,
    home: Path,
    bin_dir: Path,
    *arguments: str,
) -> subprocess.CompletedProcess[str]:
    environment = os.environ.copy()
    environment["HOME"] = str(home)
    environment["PATH"] = str(bin_dir)
    return subprocess.run(
        [
            sys.executable,
            "-m",
            "scripts.runtime",
            "--repo-root",
            str(repo_root),
            *arguments,
        ],
        cwd=Path(__file__).resolve().parents[1],
        env=environment,
        check=False,
        capture_output=True,
        text=True,
    )


def test_runtime_dry_run_reports_owned_refresh_without_writing(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("mise", "starship", "atuin", "codex", "git", "bat"):
        _fake_tool(bin_dir, name)

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--dry-run",
        "--json",
    )

    assert completed.returncode == 0
    document = json.loads(completed.stdout)
    assert document["schema_version"] == 1
    assert document["operation"] == "runtime"
    assert document["dry_run"] is True
    steps = {step["name"]: step for step in document["steps"]}
    assert steps["function.mise"]["action"] == "generate"
    assert steps["function.starship"]["status"] == "planned"
    assert steps["function.atuin"]["status"] == "planned"
    assert steps["completion.codex"]["action"] == "generate"
    assert steps["completion.op"]["status"] == "skipped"
    assert steps["plugin.fzf-tab"]["action"] == "clone"
    assert steps["plugin.zsh-autosuggestions"]["action"] == "clone"
    assert steps["plugin.fast-syntax-highlighting"]["action"] == "clone"
    assert steps["wasm.zellij-sessionizer"]["action"] == "download"
    assert steps["wasm.zjstatus"]["action"] == "download"
    assert steps["bat.cache"]["status"] == "planned"
    assert steps["zsh.compdump"]["status"] == "skipped"
    assert not (repo_root / "generated").exists()


def test_runtime_offline_apply_generates_and_removes_owned_shell_files(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    completions = repo_root / "generated/completions"
    completions.mkdir(parents=True)
    home.mkdir()
    bin_dir.mkdir()
    stale_completion = completions / "_op"
    stale_completion.write_text("stale\n")
    legacy_try_rs = completions / "_try-rs"
    legacy_try_rs.write_text("legacy\n")
    compdump = home / ".zcompdump-test"
    compdump.write_text("cache\n")
    for name in ("mise", "starship", "atuin", "codex"):
        _fake_tool(bin_dir, name, f"printf 'generated by {name}: %s\\n' \"$*\"\n")

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--offline",
        "--json",
    )

    assert completed.returncode == 0
    document = json.loads(completed.stdout)
    assert document["dry_run"] is False
    assert document["ok"] is True
    results = {step["name"]: step for step in document["steps"]}
    assert results["function.mise"]["status"] == "succeeded"
    assert results["completion.codex"]["status"] == "succeeded"
    assert results["completion.op"]["action"] == "remove"
    assert results["completion.op"]["status"] == "succeeded"
    assert results["plugin.fzf-tab"]["status"] == "skipped"
    assert results["wasm.zjstatus"]["status"] == "skipped"
    assert (repo_root / "generated/functions/_mise.zsh").read_text() == (
        "generated by mise: activate zsh\n"
    )
    assert (completions / "_codex").read_text() == (
        "generated by codex: completion zsh\n"
    )
    assert not stale_completion.exists()
    assert not legacy_try_rs.exists()
    assert not compdump.exists()


def test_runtime_generates_llm_completion_through_uvx(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    completion = repo_root / "generated/completions/_llm"
    completion.parent.mkdir(parents=True)
    completion.write_text("stale\n")
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(
        bin_dir,
        "uvx",
        'test "$1" = --offline || exit 9\n'
        'test "$2" = llm || exit 7\n'
        'test "$_LLM_COMPLETE" = zsh_source || exit 8\n'
        "printf 'llm completion\\n'\n",
    )

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--json")

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["completion.llm"]["status"] == "succeeded"
    assert steps["completion.llm"]["command"] == ["uvx", "--offline", "llm"]
    assert completion.read_text() == "llm completion\n"


def test_runtime_rejects_invalid_download_without_replacing_asset(
    tmp_path: Path,
) -> None:
    target = tmp_path / "plugin.wasm"
    target.write_bytes(b"known-good")
    expected = hashlib.sha256(b"new-valid").hexdigest()
    spec = RuntimeSpec(
        name="wasm.test",
        tool=None,
        target=target,
        source="https://example.invalid/plugin.wasm",
        sha256=expected,
    )
    plan = RuntimeReport(
        dry_run=True,
        results=(RuntimeResult(spec, RuntimeStatus.PLANNED, RuntimeAction.DOWNLOAD),),
    )

    report = execute_runtime(
        plan,
        tmp_path,
        downloader=lambda _source, _timeout: b"corrupt",
    )

    assert report.ok is False
    assert report.results[0].status is RuntimeStatus.FAILED
    assert "checksum mismatch" in (report.results[0].reason or "")
    assert target.read_bytes() == b"known-good"


def test_runtime_build_plan_owns_custom_rust_binaries(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("git", "cargo"):
        _fake_tool(bin_dir, name)

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--dry-run",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["source.atuin"]["action"] == "clone"
    assert steps["binary.atuin"]["action"] == "build"
    assert steps["source.op-cache"]["action"] == "clone"
    assert steps["binary.op-cache"]["action"] == "build"
    assert steps["binary.atuin"]["target"] == str(repo_root / "generated/bin/atuin")
    assert not (repo_root / "generated/sources").exists()


def test_runtime_build_installs_artifacts_from_portable_sources(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("atuin", "op-cache"):
        (repo_root / "generated/sources" / name / ".git").mkdir(parents=True)
    _fake_tool(
        bin_dir,
        "cargo",
        'case "$PWD" in\n'
        "  */atuin) binary=atuin ;;\n"
        "  */op-cache) binary=op-cache ;;\n"
        "esac\n"
        "/bin/mkdir -p target/release\n"
        'printf \'built %s\\n\' "$binary" > "target/release/$binary"\n'
        '/bin/chmod 755 "target/release/$binary"\n',
    )

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--offline",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["source.atuin"]["status"] == "skipped"
    assert steps["binary.atuin"]["status"] == "succeeded"
    assert steps["binary.op-cache"]["status"] == "succeeded"
    assert (repo_root / "generated/bin/atuin").read_text() == "built atuin\n"
    assert (repo_root / "generated/bin/op-cache").read_text() == "built op-cache\n"


def test_runtime_does_not_build_from_stale_source_after_update_failure(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("atuin", "op-cache"):
        (repo_root / "generated/sources" / name / ".git").mkdir(parents=True)
    _fake_tool(bin_dir, "git", "exit 7\n")
    _fake_tool(bin_dir, "cargo", "touch build-ran\n")

    completed = _run_runtime(repo_root, home, bin_dir, "--build", "--json")

    assert completed.returncode == 1
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["source.atuin"]["status"] == "failed"
    assert steps["binary.atuin"]["status"] == "skipped"
    assert "source.atuin failed" in steps["binary.atuin"]["reason"]
    assert not (repo_root / "generated/sources/atuin/build-ran").exists()
    assert not (repo_root / "generated/sources/op-cache/build-ran").exists()


def test_runtime_offline_build_is_locked_and_offline(tmp_path: Path) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    (repo_root / "generated/sources/atuin/.git").mkdir(parents=True)
    (repo_root / "generated/sources/op-cache/.git").mkdir(parents=True)
    _fake_tool(bin_dir, "cargo")

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--offline",
        "--dry-run",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    for name in ("atuin", "op-cache"):
        command = steps[f"binary.{name}"]["command"]
        assert "--locked" in command
        assert "--offline" in command


def test_runtime_online_build_requires_git_to_refresh_existing_source(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    for name in ("atuin", "op-cache"):
        (repo_root / "generated/sources" / name / ".git").mkdir(parents=True)
    _fake_tool(bin_dir, "cargo")

    completed = _run_runtime(
        repo_root,
        home,
        bin_dir,
        "--build",
        "--dry-run",
        "--json",
    )

    assert completed.returncode == 0
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["source.atuin"]["status"] == "skipped"
    assert steps["binary.atuin"]["status"] == "skipped"
    assert steps["binary.atuin"]["reason"] == "git is not available"


def test_runtime_human_mode_announces_work_and_reports_failure_to_stderr(
    tmp_path: Path,
) -> None:
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    _fake_tool(bin_dir, "mise", "exit 7\n")
    _fake_tool(bin_dir, "codex", "printf 'codex completion\\n'\n")

    completed = _run_runtime(repo_root, home, bin_dir, "--offline")

    assert completed.returncode == 1
    assert completed.stdout.splitlines()[0] == ("RUN function.mise: mise activate zsh")
    assert "[function.mise] FAIL command exited 7" in completed.stderr
    assert (repo_root / "generated/completions/_codex").read_text() == (
        "codex completion\n"
    )


def test_runtime_cli_runs_real_mise_in_an_isolated_home(tmp_path: Path) -> None:
    mise = shutil.which("mise")
    if mise is None:
        raise AssertionError("mise is required to verify this repository")
    repo_root = tmp_path / "dotfiles"
    home = tmp_path / "home"
    bin_dir = tmp_path / "bin"
    home.mkdir()
    bin_dir.mkdir()
    (bin_dir / "mise").symlink_to(Path(mise).resolve())

    completed = _run_runtime(repo_root, home, bin_dir, "--offline", "--json")

    assert completed.returncode == 0, completed.stderr
    steps = {step["name"]: step for step in json.loads(completed.stdout)["steps"]}
    assert steps["function.mise"]["status"] == "succeeded"
    activation = repo_root / "generated/functions/_mise.zsh"
    assert activation.is_file()
    assert "mise" in activation.read_text()
