[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["bat", "fd"]

[source]
command = ["fd -t f", "fd -t f -H"]

[preview]
command = "bat -n --color=always '{}'"
# env = { BAT_THEME = "ansi" }

[keybindings]
shortcut = "f1"
