[metadata]
name = "modified-files"
description = "Find modified files"
requirements = ["bat", "fd"]

[source]
command = """
{
  git diff --name-only --diff-filter=AM
  git diff --name-only --cached --diff-filter=AM
  git ls-files -o --exclude-standard
} | sort -u
"""

[preview]
command = "bat -n --color=always '{}'"
