[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
zig = "latest"

"cargo:https://github.com/clouedoc/hzfind" = "latest"
"cargo:https://github.com/immanuwell/dockerfile-roast" = "latest"
"cargo:sigye" = "latest"
"gem:kamal" = "latest"
"github:actionbook/actionbook" = "latest"
"github:larksuite/cli" = "latest"
"github:Loongphy/codex-auth" = "latest"
"github:schpet/linear-cli" = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
"go:github.com/xdevplatform/xurl" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:claude-code-sync" = "latest"
"npm:codex-sync" = "latest"
"npm:cursor-opensync-plugin" = "latest"
"npm:opencode-sync-plugin" = "latest"
"npm:pi-opensync-plugin" = "latest"
pnpm = "latest"
yarn = "latest"

[settings]
trusted_config_paths = [
    "~/Desktop",
    "~/Documents",
    "~/Downloads/",
    "~/Developer",
]

[settings.ruby]
compile = false

[env]
_.path = [
    "~/dotfiles/generated/bin",
    "~/dotfiles/modules/bin",
    "~/.bun/bin",
    "~/.local/bin",
    "/opt/homebrew/opt/postgresql@18/bin",
]

MISE_AQUA_GITHUB_ATTESTATIONS = false
