notARepository: "quit"
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --paging=never
    # externalDiffCommand: difft
gui:
  mouseEvents: false
  sidePanelWidth: 0.3
  scrollHeight: 20
