notARepository: "quit"
promptToReturnFromSubprocess: false
git:
  paging:
    externalDiffCommand: difft --color=always --display=side-by-side-show-both --syntax-highlight=off
gui:
  mouseEvents: false
  sidePanelWidth: 0.3
  scrollHeight: 20
