command_chaining = true
ctrl_n_shortcuts = true
exit_mode = "return-query"
history_filter = ["^secret-cmd", "^innocuous-cmd .*--secret=.+", "^#.*", "^\\s"]
search_mode = "daemon-fuzzy"
show_help = false

[daemon]
autostart = true
enabled = true
